### ISSUE TITLE
Recording concatenation; record timings

### ISSUE THREAD

**Issue by bigstas** [danrouse/react-audio-recorder#1]
I've just tried using this and had a bunch of problems. I'm using it with React v0.14.8 and Meteor v1.3.
- When I record, stop recording, press "remove", and record again, then the audio is now a concatenation of the previous pieces of audio.
- There is usually a roughly 3-second delay between the end of the audio and the button changing from "Playing" back to "Play".
- Sometimes, when I press play, then it plays the audio twice within about 1 second of itself. So if it's e.g. 10 seconds long, then you have the audio overlapping itself (one starts at t=0 and ends at t=10; the other starts at t=1 and ends at t=11).

**Comment by danrouse** [comment]
This is finally fixed in https://github.com/danrouse/react-audio-recorder/releases/tag/v2.0.0 - audio nodes _and_ the audio data buffer were not being cleaned up when recording stopped.
