### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by samechikson** [danrouse/react-audio-recorder#12]
When I run my very simple app created with 'create-react-app' and add the dependencies, I get the following error in my main js file:

`Module not found: 'react-audio-recorder' `

Using:
node v7.10.0
yarn v0.24.4
MacOS Sierra 10.12.3

**Comment by dbraynard** [comment]
@samechikson , it looks like the package wasn't built before getting posted to npm. I git cloned the project then set the npm package.json dependency to: `"react-audio-recorder": "file:c:/gitlab/react-audio-recorder"` and things worked.

**Comment by milani** [comment]
@danrouse Can you please upload a working version to npm?

**Comment by GavinThomas1192** [comment]
@danrouse Please can you upload a working version to npm?!

**Comment by danrouse** [comment]
@GavinThomas1192  sorry for the downtime here, I never expect anyone else to mess with my random JS projects.
This was missing `.npmignore` and the default generated `.gitignore` was greedy enough to exclude `dist` when publishing to npm. Fixed now (`2.0.1`)

**Comment by ChardXu** [comment]
> yarn

@samechikson I had try your method and  nothing work. 
 and I  found it not work  in "RunKit", should you solve this problem . hurry up
[react-audio-recorder runkit](https://npm.runkit.com/react-audio-recorder)
