### ISSUE TITLE
Error React !

### ISSUE THREAD

**Issue by vlade2008** [danrouse/react-audio-recorder#15]
Uncaught ReferenceError: React is not defined.

**Comment by vlade2008** [comment]
![image](https://user-images.githubusercontent.com/13525454/36777421-5e8f0e90-1ca4-11e8-92d3-42da1fe0befc.png)

**Comment by bzitzow** [comment]
@vlade2008 did this solve your issue?

> @vlade2008 You may just need to do
> 
> ```js
> import * as React from 'react'
> ```
> 
> or
> 
> ```
> const React = require('react')
> ```
> based on your build system's configuration wherever you use this module

**Comment by bzitzow** [comment]
Closing issue as it is not a problem with `react-audio-recorder`.
