### ISSUE TITLE
Errors on changing tab

### ISSUE THREAD

**Issue by bigstas** [danrouse/react-audio-recorder#2]
If you press "Play" and then change tab (using React Router), and then you try to return to the tab in which you have the AudioRecorder, you get the following errors:

Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.
Uncaught NotSupportedError: Failed to construct 'AudioContext': The number of hardware contexts provided (6) is greater than or equal to the maximum bound (6).
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.
Uncaught TypeError: Cannot read property 'componentWillUnmount' of null

Then it won't let you return to the recording tab.

**Comment by danrouse** [comment]
This is finally fixed in https://github.com/danrouse/react-audio-recorder/releases/tag/v2.0.0 - the audio context is shared through all instances of the component.
