### ISSUE TITLE
Any idea about how to upload the audio file to server?

### ISSUE THREAD

**Issue by omidfi** [danrouse/react-audio-recorder#3]
Thanks for the nice component, I was wondering if someone knows how to upload the recorded file to server

**Comment by omidfi** [comment]
Solved.

**Comment by AmanKrishna** [comment]
@albacoretuna can you please share how you solved it?

**Comment by albacoretuna** [comment]
I made a sample app that uploads the files to a nodejs service, you can check it out here: 

https://github.com/albacoretuna/sayitlikeme

Let me know if something is unclear. It was a while ago so I'm not sure what I did at the end :)

**Comment by AmanKrishna** [comment]
Thank you for your help
