### ISSUE TITLE
Can I use this package in React-Native ?

### ISSUE THREAD

**Issue by nileshprajapati007444** [danrouse/react-audio-recorder#30]
I want to record audio from user speak in wav file. Can I use this package in react-native application ?

Can we auto stop recording when user stop speaking ?

Can you please help me for my this query ?

Thanks in advance.

**Comment by bzitzow** [comment]
Hi niles. React Audio Recorder uses the browsers [Web Audio API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API) and therefore will not work for native devices.
