### ISSUE TITLE
New record doestn't work 

### ISSUE THREAD

**Issue by ShuvoHabib** [danrouse/react-audio-recorder#4]
After removing record New record doestn't work , it plays the old recorded audio again.. Cache is not cleared fully when 'Remove' is clicked. Because after clicking 'Remove', New record doesn't work.

**Comment by danrouse** [comment]
This is finally fixed in https://github.com/danrouse/react-audio-recorder/releases/tag/v2.0.0 -- buffers were not being properly destroyed.
