### ISSUE TITLE
Issue When Remove Already Recorded Audio

### ISSUE THREAD

**Issue by superKalo** [danrouse/react-audio-recorder#9]
Here are the reproduction steps:

1. Record audio. Play it (preview). All good.
2. Then Remove it. Then Record another one. Play it (preview).

It plays the previous (deleted) audio, not the new one (the second). Moreover, after playing the deleted audio it plays the new one (the second) on slow motion.

**Comment by danrouse** [comment]
This is finally fixed in https://github.com/danrouse/react-audio-recorder/releases/tag/v2.0.0 - the buffer wasn't being cleared properly, _and_ the audio recording node wasn't disconnected, so it continued to pour data into new buffers.
